name: Pet

on:
  workflow_dispatch
  schedule:
    - cron:  '0 */6 * * *'

jobs:
  pet:
    env:
      PRIVATE_KEY: ${{ secrets.PrivateKey }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: yarn tsc index.ts
      - run: node index.js
